#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Starting application
$HOME/.config/polybar/launch.sh
# picom &

# Setting up wallpaper
feh --bg-scale ~/Pictures/wallpapers/nord/004.jpg &
# Updating image for lockscreen
# betterlockscreen -u ~/Documents/wallpapers/nord/004.jpg & 

# Inverting scrolling
#
# Get id of touchpad and the id of the field corresponding to
# natural scrolling
id=`xinput list | grep -i "Touchpad" | cut -d'=' -f2 | cut -d'[' -f1`
natural_scrolling_id=`xinput list-props $id | \
                      grep -i "Natural Scrolling Enabled (" \
                      | cut -d'(' -f2 | cut -d')' -f1`

# Set the property to true
xinput --set-prop $id $natural_scrolling_id 1


# Setting up bspwm

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap           12

bspc config focused_border_color \#81A1C1
bspc config normal_border_color  \#4C566A
bspc config presel_feedback_color \#5E81AC

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# Setting rules

bspc rule -a Zathura state=tiled
bspc rule -a Zoom state=floating
